name: build_hise
on: [push]
jobs:
  build-hise:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout HISE repository
        uses: actions/checkout@v1
      - name: Build HISE
        run: ${{ github.workspace }}/tools/auto_build/01_BuildHISE.bat
        shell: cmd
