name: build_hise
on: [push]
jobs:
  build-hise:
    runs-on: [self-hosted, windows]
    steps:
      - name: Run build script
      - uses: actions/checkout@v1
      - run: /tools/auto_build/01_BuildHISE.bat
        shell: cmd
