name: build_hise
on: [push]
jobs:
  build-hise:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout HISE repository
        uses: actions/checkout@v1
      - name: Extract SDK
        working-directory: ${{ github.workspace }}/tools/SDK/
        run: tar -xf sdk.zip
      - name: Build HISE
        working-directory: ${{ github.workspace }}/tools/auto_build/
        run: 01_BuildHISE.bat
        shell: cmd
